/* Robin static demo mode -- for GitHub Pages, where there is no Python
 * backend at all. Detects that it's running without a real server and
 * monkey-patches window.fetch + window.EventSource so every /api/* call
 * the app already makes gets a plausible canned answer instead of a
 * network error, using the SAME response shapes the real server returns
 * (jobs/pipeline/metrics fixtures below were generated by running the
 * real backend code -- ats_jobs._normalized_to_card, pipeline_store,
 * metrics.all_metrics -- against a throwaway seeded DB, then captured;
 * they are not hand-guessed).
 *
 * Onboarding needs almost none of this: getOnboardingSpec() is pure
 * client-side JS already, and kg_store's isOnboardingComplete/
 * saveOnboardingAnswers already fail silently offline by design. This
 * file exists mainly for the MAIN APP screens (Browse, Apply, Knowledge
 * Graph, Metrics, Profile), which have real backend dependencies.
 *
 * Everything here lives in this one file so exactly one thing can drift
 * out of date with the real API, not six files scattered with ad hoc
 * mock branches.
 */
(function () {
  'use strict';

  var params = new URLSearchParams(location.search);
  var isDemo = params.get('demo') === '1' || /(^|\.)github\.io$/.test(location.hostname);
  if (!isDemo) return;

  window.__ROBIN_DEMO__ = true;

  // ---------------------------------------------------------------------
  // In-memory "server" state -- lets a POST during this session (e.g. the
  // onboarding front door saving KG answers, or Profile edits) actually
  // stick for the rest of the walkthrough, without needing a real backend.
  // Resets on reload. Never persisted anywhere.
  // ---------------------------------------------------------------------
  var STATE = {
    kgIndividual: null, // lazy-loaded from kg/individual.default.json
    profile: {
      ok: true,
      profile: {
        firstName: 'Alex', lastName: 'Rivera', email: 'you@example.com',
        phone: '', city: 'San Francisco', state: 'CA',
        linkedin: 'https://www.linkedin.com/in/example-alex-rivera',
        github: '', portfolio: 'https://example.com/alex-rivera',
        skills: ['Figma', 'Design systems', 'Prototyping', 'User research', 'Interaction design'],
        experience: [
          { company: 'Vantage Studio', title: 'Senior Product Designer', bullets: [
            'Led design for a B2B analytics dashboard used by 40k weekly actives.',
            'Built and maintained the company-wide design system in Figma.',
          ] },
          { company: 'Brightline Co', title: 'Product Designer', bullets: [
            'Owned onboarding redesign, cutting time-to-first-value by 30%.',
          ] },
        ],
        education: [{ degree: 'BFA, Interaction Design', school: 'California College of the Arts' }],
        languages: ['English'],
      },
      modules: ['scout', 'screen', 'fit', 'tailor', 'cover', 'humanize', 'compile', 'apply_external', 'log'],
      titles: ['Product Designer', 'UX Designer', 'Senior Product Designer'],
    },
  };

  function clone(x) { return JSON.parse(JSON.stringify(x)); }

  // ---------------------------------------------------------------------
  // Rich fixtures -- generated from the real backend, not hand-written.
  // See .devcontainer / README for how a visitor gets the REAL versions
  // of these (Codespaces badge, live agents, their own API key).
  // ---------------------------------------------------------------------
  var JOBS_FIXTURE = {
  "jobs": [
    {
      "id": "gh-northwind-northwind-senior-product-designer",
      "title": "Senior Product Designer",
      "company": "Northwind Devices",
      "location": "Remote (US)",
      "remote": true,
      "workplace": "remote",
      "ats_source": "greenhouse",
      "job_url": "https://example.com/jobs/northwind-senior-product-designer",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Greenhouse",
        "Remote"
      ],
      "letter": "N",
      "bg": "from-orange-600 to-red-500",
      "color": "#27a644",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Own end-to-end design for our developer-tools suite, from discovery through shipped UI. You&#x27;ll partner directly with two staff engineers and a PM.</p>",
      "description": "Own end-to-end design for our developer-tools suite, from discovery through shipped UI. You'll partner directly with two staff engineers and a PM.",
      "detail": {
        "board": "greenhouse",
        "slug": "northwind",
        "job_id": "northwind-senior-product-designer"
      },
      "needs_detail": false
    },
    {
      "id": "lv-cedar-health-cedar-product-designer-health",
      "title": "Product Designer, Health",
      "company": "Cedar Health Labs",
      "location": "Austin, TX",
      "remote": false,
      "workplace": "hybrid",
      "ats_source": "lever",
      "job_url": "https://example.com/jobs/cedar-product-designer-health",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Lever",
        "Hybrid"
      ],
      "letter": "C",
      "bg": "from-slate-700 to-slate-600",
      "color": "#8b5cf6",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Design patient-facing flows for a clinical scheduling product used by 200+ clinics. HIPAA-aware design experience a plus.</p>",
      "description": "Design patient-facing flows for a clinical scheduling product used by 200+ clinics. HIPAA-aware design experience a plus.",
      "detail": {
        "board": "lever",
        "slug": "cedar-health",
        "job_id": "cedar-product-designer-health"
      },
      "needs_detail": false
    },
    {
      "id": "as-acme-labs-acme-ux-designer",
      "title": "UX Designer",
      "company": "Acme Labs",
      "location": "San Francisco, CA",
      "remote": false,
      "workplace": "onsite",
      "ats_source": "ashby",
      "job_url": "https://example.com/jobs/acme-ux-designer",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Ashby",
        "Onsite"
      ],
      "letter": "A",
      "bg": "from-slate-700 to-slate-600",
      "color": "#0ea5e9",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Partner with PM and eng on the core workspace experience for a Series C analytics platform.</p>",
      "description": "Partner with PM and eng on the core workspace experience for a Series C analytics platform.",
      "detail": {
        "board": "ashby",
        "slug": "acme-labs",
        "job_id": "acme-ux-designer"
      },
      "needs_detail": false
    },
    {
      "id": "wk-lumen-lumen-staff-product-designer",
      "title": "Staff Product Designer",
      "company": "Lumen Interfaces",
      "location": "Remote (Global)",
      "remote": true,
      "workplace": "remote",
      "ats_source": "workable",
      "job_url": "https://example.com/jobs/lumen-staff-product-designer",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Workable",
        "Remote"
      ],
      "letter": "L",
      "bg": "from-emerald-600 to-teal-600",
      "color": "#2d9cdb",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Lead design systems strategy across three product lines; mentor two mid-level designers.</p>",
      "description": "Lead design systems strategy across three product lines; mentor two mid-level designers.",
      "detail": {
        "board": "workable",
        "slug": "lumen",
        "job_id": "lumen-staff-product-designer"
      },
      "needs_detail": false
    },
    {
      "id": "gh-fieldstone-fieldstone-product-designer",
      "title": "Product Designer",
      "company": "Fieldstone Robotics",
      "location": "Pittsburgh, PA",
      "remote": false,
      "workplace": "hybrid",
      "ats_source": "greenhouse",
      "job_url": "https://example.com/jobs/fieldstone-product-designer",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Greenhouse",
        "Hybrid"
      ],
      "letter": "F",
      "bg": "from-orange-600 to-red-500",
      "color": "#27a644",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Design the operator console for warehouse robotics hardware, from concept to field test.</p>",
      "description": "Design the operator console for warehouse robotics hardware, from concept to field test.",
      "detail": {
        "board": "greenhouse",
        "slug": "fieldstone",
        "job_id": "fieldstone-product-designer"
      },
      "needs_detail": false
    },
    {
      "id": "rmt-36b4e2303c9c",
      "title": "Product Designer, Growth",
      "company": "Harbor & Co",
      "location": "Remote (US)",
      "remote": true,
      "workplace": "remote",
      "ats_source": "remotive",
      "job_url": "https://example.com/jobs/harbor-growth-designer",
      "posted_at": "2026-08-29T12:00:00Z",
      "tags": [
        "Remotive",
        "Remote"
      ],
      "letter": "H",
      "bg": "from-sky-600 to-blue-600",
      "color": "#1e90ff",
      "isNew": true,
      "desc": "<p class=\"mb-3\">Own onboarding and activation flows for a consumer fintech app with 2M+ monthly actives.</p>",
      "description": "Own onboarding and activation flows for a consumer fintech app with 2M+ monthly actives.",
      "detail": null,
      "needs_detail": false
    }
  ],
  "adjacent": [],
  "dropped": 0,
  "role": {},
  "total": 6,
  "sources_used": [
    "ashby",
    "greenhouse",
    "lever",
    "remotive",
    "workable"
  ],
  "watchlist": {}
};

  var PIPELINE_FIXTURE = {
  "ok": true,
  "order": [
    "discovered",
    "scored",
    "tailored",
    "applied",
    "replied",
    "interview",
    "offer",
    "rejected",
    "skipped",
    "failed"
  ],
  "stages": [
    "scouted",
    "screened",
    "scored",
    "tailored",
    "cover",
    "humanized",
    "compiled",
    "applied",
    "logged",
    "replied",
    "interview",
    "offer",
    "skipped",
    "rejected",
    "failed"
  ],
  "pipeline": {
    "discovered": [
      {
        "id": 1,
        "job_id": 1,
        "run_id": "demo-seed",
        "status": "discovered",
        "fit_score": null,
        "tailored": 0,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.251071+00:00",
        "updated_at": "2026-08-31T01:45:56.261144+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "scouted",
        "title": "Senior Product Designer",
        "company": "Northwind Devices",
        "location": "Remote (US)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/northwind-senior-product-designer",
        "posted_at": null
      }
    ],
    "scored": [
      {
        "id": 2,
        "job_id": 2,
        "run_id": "demo-seed",
        "status": "scored",
        "fit_score": 82,
        "tailored": 0,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.270919+00:00",
        "updated_at": "2026-08-31T01:45:56.282705+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "scored",
        "title": "Product Designer, Health",
        "company": "Cedar Health Labs",
        "location": "Austin, TX",
        "work_mode": "hybrid",
        "url": "https://example.com/jobs/cedar-product-designer-health",
        "posted_at": null
      }
    ],
    "tailored": [
      {
        "id": 4,
        "job_id": 4,
        "run_id": "demo-seed",
        "status": "tailored",
        "fit_score": 91,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.313826+00:00",
        "updated_at": "2026-08-31T01:45:56.325479+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "cover",
        "title": "Staff Product Designer",
        "company": "Lumen Interfaces",
        "location": "Remote (Global)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/lumen-staff-product-designer",
        "posted_at": null
      },
      {
        "id": 3,
        "job_id": 3,
        "run_id": "demo-seed",
        "status": "tailored",
        "fit_score": 88,
        "tailored": 1,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.292266+00:00",
        "updated_at": "2026-08-31T01:45:56.304375+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "tailored",
        "title": "UX Designer",
        "company": "Acme Labs",
        "location": "San Francisco, CA",
        "work_mode": "onsite",
        "url": "https://example.com/jobs/acme-ux-designer",
        "posted_at": null
      }
    ],
    "applied": [
      {
        "id": 5,
        "job_id": 5,
        "run_id": "demo-seed",
        "status": "applied",
        "fit_score": 90,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.335441+00:00",
        "updated_at": "2026-08-31T01:45:56.347477+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "applied",
        "title": "Product Designer",
        "company": "Fieldstone Robotics",
        "location": "Pittsburgh, PA",
        "work_mode": "hybrid",
        "url": "https://example.com/jobs/fieldstone-product-designer",
        "posted_at": null
      }
    ],
    "replied": [
      {
        "id": 6,
        "job_id": 6,
        "run_id": "demo-seed",
        "status": "replied",
        "fit_score": 94,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.356514+00:00",
        "updated_at": "2026-08-31T01:45:56.369571+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "replied",
        "title": "Product Designer, Growth",
        "company": "Harbor & Co",
        "location": "Remote (US)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/harbor-growth-designer",
        "posted_at": null
      }
    ],
    "interview": [],
    "offer": [],
    "rejected": [],
    "skipped": [],
    "failed": []
  },
  "by_stage": {
    "scouted": [
      {
        "id": 1,
        "job_id": 1,
        "run_id": "demo-seed",
        "status": "discovered",
        "fit_score": null,
        "tailored": 0,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.251071+00:00",
        "updated_at": "2026-08-31T01:45:56.261144+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "scouted",
        "title": "Senior Product Designer",
        "company": "Northwind Devices",
        "location": "Remote (US)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/northwind-senior-product-designer",
        "posted_at": null
      }
    ],
    "screened": [],
    "scored": [
      {
        "id": 2,
        "job_id": 2,
        "run_id": "demo-seed",
        "status": "scored",
        "fit_score": 82,
        "tailored": 0,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.270919+00:00",
        "updated_at": "2026-08-31T01:45:56.282705+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "scored",
        "title": "Product Designer, Health",
        "company": "Cedar Health Labs",
        "location": "Austin, TX",
        "work_mode": "hybrid",
        "url": "https://example.com/jobs/cedar-product-designer-health",
        "posted_at": null
      }
    ],
    "tailored": [
      {
        "id": 3,
        "job_id": 3,
        "run_id": "demo-seed",
        "status": "tailored",
        "fit_score": 88,
        "tailored": 1,
        "cover_letter": 0,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.292266+00:00",
        "updated_at": "2026-08-31T01:45:56.304375+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "tailored",
        "title": "UX Designer",
        "company": "Acme Labs",
        "location": "San Francisco, CA",
        "work_mode": "onsite",
        "url": "https://example.com/jobs/acme-ux-designer",
        "posted_at": null
      }
    ],
    "cover": [
      {
        "id": 4,
        "job_id": 4,
        "run_id": "demo-seed",
        "status": "tailored",
        "fit_score": 91,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.313826+00:00",
        "updated_at": "2026-08-31T01:45:56.325479+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "cover",
        "title": "Staff Product Designer",
        "company": "Lumen Interfaces",
        "location": "Remote (Global)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/lumen-staff-product-designer",
        "posted_at": null
      }
    ],
    "humanized": [],
    "compiled": [],
    "applied": [
      {
        "id": 5,
        "job_id": 5,
        "run_id": "demo-seed",
        "status": "applied",
        "fit_score": 90,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.335441+00:00",
        "updated_at": "2026-08-31T01:45:56.347477+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "applied",
        "title": "Product Designer",
        "company": "Fieldstone Robotics",
        "location": "Pittsburgh, PA",
        "work_mode": "hybrid",
        "url": "https://example.com/jobs/fieldstone-product-designer",
        "posted_at": null
      }
    ],
    "logged": [],
    "replied": [
      {
        "id": 6,
        "job_id": 6,
        "run_id": "demo-seed",
        "status": "replied",
        "fit_score": 94,
        "tailored": 1,
        "cover_letter": 1,
        "resume_pdf_url": null,
        "cover_doc_url": null,
        "applied_at": null,
        "created_at": "2026-08-31T01:45:56.356514+00:00",
        "updated_at": "2026-08-31T01:45:56.369571+00:00",
        "notes": "",
        "dry_run": 1,
        "ats_before": null,
        "ats_after": null,
        "board_stage": "replied",
        "title": "Product Designer, Growth",
        "company": "Harbor & Co",
        "location": "Remote (US)",
        "work_mode": "remote",
        "url": "https://example.com/jobs/harbor-growth-designer",
        "posted_at": null
      }
    ],
    "interview": [],
    "offer": [],
    "skipped": [],
    "rejected": [],
    "failed": []
  },
  "counts": {
    "discovered": 1,
    "scored": 1,
    "tailored": 2,
    "applied": 1,
    "replied": 1,
    "interview": 0,
    "offer": 0,
    "rejected": 0,
    "skipped": 0,
    "failed": 0
  },
  "stage_counts": {
    "scouted": 1,
    "screened": 0,
    "scored": 1,
    "tailored": 1,
    "cover": 1,
    "humanized": 0,
    "compiled": 0,
    "applied": 1,
    "logged": 0,
    "replied": 1,
    "interview": 0,
    "offer": 0,
    "skipped": 0,
    "rejected": 0,
    "failed": 0
  },
  "pending": [],
  "home_country": "US"
};

  var METRICS_FIXTURE = {
  "ok": true,
  "range_days": 30,
  "state": "S1",
  "efficiency": {
    "has_data": false,
    "tokens_per_run": null,
    "cost_per_run": null,
    "cost_per_application": null,
    "tokens_by_agent": [],
    "retries_by_agent": [],
    "run_duration": null,
    "cost_over_time": [],
    "runs": []
  },
  "reach": {
    "has_data": true,
    "jobs_discovered": 6,
    "jobs_discovered_has_data": true,
    "unique_companies": 6,
    "sources_live": null,
    "sources_quarantined": null,
    "dedupe_rate": {
      "has_data": false,
      "value": null,
      "job_source_rows": 0,
      "distinct_jobs": 0
    },
    "jobs_per_source": [],
    "jobs_over_time": [
      {
        "day": "2026-08-31",
        "count": 6
      }
    ],
    "sources": []
  },
  "quality": {
    "has_data": true,
    "fit_score_histogram": [
      {
        "bin_start": 0,
        "bin_end": 10,
        "count": 0
      },
      {
        "bin_start": 10,
        "bin_end": 20,
        "count": 0
      },
      {
        "bin_start": 20,
        "bin_end": 30,
        "count": 0
      },
      {
        "bin_start": 30,
        "bin_end": 40,
        "count": 0
      },
      {
        "bin_start": 40,
        "bin_end": 50,
        "count": 0
      },
      {
        "bin_start": 50,
        "bin_end": 60,
        "count": 0
      },
      {
        "bin_start": 60,
        "bin_end": 70,
        "count": 0
      },
      {
        "bin_start": 70,
        "bin_end": 80,
        "count": 0
      },
      {
        "bin_start": 80,
        "bin_end": 90,
        "count": 2
      },
      {
        "bin_start": 90,
        "bin_end": 100,
        "count": 3
      }
    ],
    "median_fit_score": 90,
    "pct_above_threshold": 1,
    "scored_count": 5,
    "tailoring_rate": 0.6666666666666666,
    "cover_letter_rate": 0.5,
    "threshold": 25,
    "application_count": 6
  },
  "funnel": {
    "has_data": false,
    "counts": {
      "discovered": null,
      "scored": null,
      "tailored": null,
      "applied": null,
      "replied": null,
      "interview": null,
      "offer": null
    },
    "stages": [
      "discovered",
      "scored",
      "tailored",
      "applied",
      "replied",
      "interview",
      "offer"
    ],
    "response_rate": null,
    "interview_rate": null,
    "offer_rate": null,
    "rejection_rate": null,
    "time_to_first_reply_median_hours": null,
    "applied": null,
    "dry_run_applied": 0,
    "rate_suppressed": true,
    "rate_hidden": true,
    "rate_suppressed_reason": "0 applications is too few for a rate to mean anything"
  },
  "time_saved": {
    "has_data": false,
    "value": null,
    "time_saved_minutes": null,
    "is_estimate": true,
    "manual_minutes_per_application": 35,
    "applications_submitted": 0,
    "run_minutes": 0
  },
  "referral": {
    "has_data": false,
    "contacts_identified": null,
    "drafts_generated": null,
    "drafts_sent": null,
    "referral_response_rate": null,
    "applications_with_referral": null,
    "coming_soon": true
  },
  "pace": {
    "has_data": false,
    "sent": 0,
    "benchmark": 42,
    "profession": "design",
    "family": "product_design",
    "first_interview_at_application": null,
    "state": "S1",
    "interview_rate_benchmark": 0.03,
    "interview_to_hire": 0.27,
    "applicants_per_hire": 95,
    "source": "ResuTrack / PitchHired 2026"
  },
  "silence": {
    "has_data": false,
    "awaiting": 0,
    "buckets": {
      "early": 0,
      "typical": 0,
      "fading": 0,
      "dead": 0
    },
    "follow_up_count": 0,
    "no_response_low": 0.48,
    "no_response_high": 0.75,
    "source": "Criteria Corp 2025; Human Capital Institute"
  },
  "cadence": {
    "has_data": false,
    "weeks": [],
    "current_streak_weeks": 0,
    "best_week": null,
    "per_week_avg": null
  },
  "pipeline": {
    "has_data": false,
    "live": 0,
    "closed": 0
  },
  "targeting": {
    "has_data": true,
    "core": 5,
    "adjacent": 0,
    "dropped": 1,
    "dropped_job_ids": [
      4
    ]
  },
  "proof_of_work": {
    "has_data": true,
    "total": 6,
    "tailored": 4,
    "cover_letters": 3,
    "resume_pdfs": 0
  },
  "ats_lift": {
    "has_data": false,
    "blocked_reason": "Runs after your first tailored application",
    "median_before": null,
    "median_after": null,
    "delta": null,
    "pairs": [],
    "above_keyword_threshold": null,
    "threshold": 0.7,
    "callback_optimized": 0.117,
    "callback_generic": 0.042,
    "tailored_multiplier": 2.5,
    "source": "15,000-application study, 2024"
  },
  "next_actions": [
    {
      "key": "ats_after_missing",
      "count": 1,
      "why": "tailoring never wrote ats_after",
      "action_label": "Fix ATS lift",
      "action_endpoint": "/api/run"
    }
  ]
};

  var RESUME_PARSE_FIXTURE = {
    ok: true,
    firstName: 'Alex', lastName: 'Rivera', email: 'you@example.com', phone: '',
    city: 'San Francisco', state: 'CA',
    linkedin: 'https://www.linkedin.com/in/example-alex-rivera', github: '',
    portfolio: 'https://example.com/alex-rivera',
    skills: ['Figma', 'Design systems', 'Prototyping', 'User research', 'Interaction design'],
    experience: [
      { company: 'Vantage Studio', title: 'Senior Product Designer', bullets: [
        'Led design for a B2B analytics dashboard used by 40k weekly actives.',
        'Built and maintained the company-wide design system in Figma.',
      ] },
      { company: 'Brightline Co', title: 'Product Designer', bullets: [
        'Owned onboarding redesign, cutting time-to-first-value by 30%.',
      ] },
    ],
    education: [{ degree: 'BFA, Interaction Design', school: 'California College of the Arts' }],
    languages: ['English'],
  };

  // ---------------------------------------------------------------------
  // Route table. `json` returns a plain object synchronously; `staticFile`
  // re-fetches a real committed file (the REAL fetch, not mocked -- these
  // are ordinary static assets GitHub Pages already serves) and wraps it.
  // First match wins. Anything under /api/ with no match falls through to
  // a generic {ok:true} so an unhandled admin endpoint fails soft, not
  // with a console error.
  // ---------------------------------------------------------------------
  function loadKgIndividual() {
    if (STATE.kgIndividual) return Promise.resolve(STATE.kgIndividual);
    return fetch('kg/individual.default.json')
      .then(function (r) { return r.json(); })
      .then(function (data) { STATE.kgIndividual = data; return data; })
      .catch(function () { STATE.kgIndividual = {}; return {}; });
  }

  var ROUTES = [
    { test: eq('/api/health'), json: function () {
      return { status: 'ok', service: 'robin-dashboard', brand: 'Robin', dry_run: true, DRY_RUN: 'True' };
    } },
    { test: eq('/api/jobs'), json: function () { return clone(JOBS_FIXTURE); } },
    { test: eq('/api/jobs/detail'), json: function () { return { ok: true }; } },
    { test: eq('/api/jobs/scan-log'), json: function () { return { ok: true, events: [] }; } },
    { test: eq('/api/pipeline'), json: function () { return clone(PIPELINE_FIXTURE); } },
    { test: eq('/api/pipeline/detail'), json: function () {
      var all = [].concat.apply([], Object.values(PIPELINE_FIXTURE.pipeline));
      var id = Number(new URLSearchParams(location.search).get('id'));
      var found = all.find(function (a) { return a.id === id; }) || all[0];
      return clone(found);
    } },
    { test: startsWith('/api/pipeline/'), json: function () { return { ok: true, application: null }; } },
    { test: eq('/api/pipeline/queue'), json: function () { return { ok: true }; } },
    { test: eq('/api/pipeline/status'), json: function () { return { ok: true }; } },
    { test: eq('/api/metrics'), json: function () { return clone(METRICS_FIXTURE); } },
    { test: eq('/api/profile'), json: function () { return clone(STATE.profile); } },
    { test: eq('/api/profile/parse'), json: function () { return clone(RESUME_PARSE_FIXTURE); } },
    { test: eq('/api/profile/resume-preview'), json: function () {
      return { ok: false, error: 'No resume uploaded yet (demo mode)' };
    } },
    { test: startsWith('/api/kg/individual'), method: 'GET', json: function () {
      return loadKgIndividual().then(function (g) { return { ok: true, graph: g }; });
    } },
    { test: startsWith('/api/kg/individual'), method: 'POST', json: function (body) {
      return loadKgIndividual().then(function () {
        try {
          var posted = JSON.parse(body || '{}');
          if (posted && posted.graph) STATE.kgIndividual = posted.graph;
        } catch (e) {}
        return { ok: true, graph: STATE.kgIndividual };
      });
    } },
    { test: eq('/api/kg/all'), json: function () {
      return fetch('kg/all.dummy.json').then(function (r) { return r.json(); })
        .then(function (g) { return { ok: true, graph: g }; })
        .catch(function () { return { ok: true, graph: {} }; });
    } },
    { test: eq('/api/kg/salary-bands'), json: function () {
      return fetch('kg/salary_bands.us.json').then(function (r) { return r.json(); })
        .then(function (g) { return Object.assign({ ok: true }, g); })
        .catch(function () { return { ok: true, bands: [] }; });
    } },
    { test: eq('/api/kg/riasec'), json: function () {
      return fetch('kg/onet/riasec_items.json').then(function (r) { return r.json(); })
        .then(function (items) { return { ok: true, items: items, result: {} }; })
        .catch(function () { return { ok: true, items: [], result: {} }; });
    } },
    { test: eq('/api/kg/work-styles'), json: function () {
      return fetch('kg/onet/work_style_items.json').then(function (r) { return r.json(); })
        .then(function (items) { return { ok: true, items: items, result: {} }; })
        .catch(function () { return { ok: true, items: [], result: {} }; });
    } },
    { test: eq('/api/kg/share'), json: function () { return { ok: true, prefs: {} }; } },
    { test: eq('/api/kg/market-pulse'), json: function () { return { ok: true, enabled: false, items: [] }; } },
    { test: eq('/api/run/status'), json: function () { return { ok: true, running: false }; } },
    { test: eq('/api/run/plan'), json: function () { return { ok: true, plan: [] }; } },
    { test: eq('/api/history'), json: function () { return { ok: true, items: [] }; } },
    { test: eq('/api/skills'), json: function () { return { ok: true, skills: [] }; } },
    { test: eq('/api/profiles'), json: function () { return { ok: true, profiles: [] }; } },
    { test: eq('/api/resume'), json: function () { return { ok: false, error: 'demo mode' }; } },
    // Everything else under /api/ -- settings, sources, models, gmail,
    // errors, autofix, schedule, chat, preview, linkedin
    // review, outcomes, abort/pause/retry/run -- a visitor exploring the
    // demo can click these; a safe no-op beats a console error.
    { test: startsWith('/api/'), json: function () { return { ok: true }; } },
  ];

  function eq(p) { return function (path) { return path === p; }; }
  function startsWith(p) { return function (path) { return path.indexOf(p) === 0; }; }

  function pathnameOf(input) {
    var raw = typeof input === 'string' ? input : (input && input.url) || '';
    try { return new URL(raw, location.href).pathname.replace(/^.*\/api\//, '/api/'); }
    catch (e) { return raw; }
  }

  var realFetch = window.fetch.bind(window);
  window.fetch = function (input, init) {
    var path = pathnameOf(input);
    if (path.indexOf('/api/') !== 0) return realFetch(input, init);
    var method = ((init && init.method) || 'GET').toUpperCase();
    var route = ROUTES.find(function (r) {
      return r.test(path) && (!r.method || r.method === method);
    });
    var body = init && init.body;
    var result = route ? route.json(body) : { ok: true };
    return Promise.resolve(result).then(function (data) {
      return new Response(JSON.stringify(data), { status: 200, headers: { 'Content-Type': 'application/json' } });
    });
  };

  // No real backend to stream from. initLiveRunSSE() only wires listeners
  // (addEventListener) and never reads readyState synchronously, so a
  // silent no-op object is enough -- the scripted playback below drives
  // the same UI functions directly instead.
  window.EventSource = function (url) {
    this.url = url;
    this.readyState = 1;
    this.addEventListener = function () {};
    this.removeEventListener = function () {};
    this.close = function () {};
  };

  // ---------------------------------------------------------------------
  // Scripted live-run playback: calls the SAME global functions real SSE
  // events would trigger (upsertLiveRunCard / renderLiveRunBoard, both
  // defined at top level in mockup.html), on a fixed timeline, so the
  // Canvas/Apply live board looks like it's watching a real run without
  // faking an actual EventSource connection.
  // ---------------------------------------------------------------------
  var SCRIPT = [
    { t: 800, col: 'discovered', card: { id: 'demo-1', company: 'Northwind Devices', title: 'Senior Product Designer' } },
    { t: 2200, col: 'discovered', card: { id: 'demo-2', company: 'Cedar Health Labs', title: 'Product Designer, Health' } },
    { t: 4200, col: 'tailoring', card: { id: 'demo-1', company: 'Northwind Devices', title: 'Senior Product Designer', score: 88 } },
    { t: 6400, col: 'tailoring', card: { id: 'demo-2', company: 'Cedar Health Labs', title: 'Product Designer, Health', score: 82 } },
    { t: 8600, col: 'review', card: { id: 'demo-1', company: 'Northwind Devices', title: 'Senior Product Designer', score: 88, note: 'Cover letter drafted', highlight: true } },
    { t: 11000, col: 'submitted', card: { id: 'demo-1', company: 'Northwind Devices', title: 'Senior Product Designer', score: 88, note: 'Applied (dry run)' } },
  ];

  function playScript() {
    if (typeof window.upsertLiveRunCard !== 'function') return;
    SCRIPT.forEach(function (step) {
      setTimeout(function () {
        try { window.upsertLiveRunCard(step.col, step.card); } catch (e) {}
      }, step.t);
    });
  }
  // The live board only exists once #kanban is in the DOM (dashboard tab).
  // Poll briefly for it rather than assuming load order between this file
  // and mockup.html's own scripts.
  var tries = 0;
  var waitForBoard = setInterval(function () {
    tries++;
    if (document.getElementById('kanban') || tries > 40) {
      clearInterval(waitForBoard);
      if (document.getElementById('kanban')) playScript();
    }
  }, 250);

  // ---------------------------------------------------------------------
  // Honesty banner -- a visitor should always know this is sample data,
  // not someone's real job search or real live agent output.
  // ---------------------------------------------------------------------
  function addBanner() {
    var el = document.createElement('div');
    el.textContent = 'Demo mode — every screen here is sample data. Nothing is a real job search.';
    el.style.cssText = 'position:fixed;left:0;right:0;bottom:0;z-index:99999;'
      + 'background:#1c1a17;color:#f1efe9;font:12px/1.4 system-ui,sans-serif;'
      + 'text-align:center;padding:6px 12px;letter-spacing:.01em;';
    document.addEventListener('DOMContentLoaded', function () { document.body.appendChild(el); });
    if (document.body) document.body.appendChild(el);
  }
  addBanner();
})();
